# Resume Generator Configuration

# General settings
general:
  input_file: "RESUME.md" 
  output_file: "resume.pdf"

# Rendering mode: "ats" for ATS-friendly or "custom" for styled
mode: "custom"

# Styling configuration
styling:
  font_family: "Arial, sans-serif"
  font_size: "12px"
  margin_size: "20px"
  theme: "nord"
