# Resume Generator Configuration
general:
  # input_file: "./artifacts/input_markdown_resumes/akhil-hft.md"
  input_file: "./artifacts/input_markdown_resumes/real-akhil.md"
  # input_file: "./artifacts/input_markdown_resumes/akhil-polyglot.md"
  output_file: "./artifacts/output_cvs/akhil-resume.pdf"

# mode: "ats"
mode: "custom"

# various styling options.
# professional.
# styling:
#   font_family: "Arial, sans-serif"
#   font_size: "10px"
#   margin_size: "4px"
#   theme: "professional"
#   custom_css_path: "./styles/professional.css"

# catppuccin-mocha
# styling:
#   font_family: "JetBrains Mono, monospace"
#   font_size: "10.0pt"
#   margin_size: "4px"
#   theme: "catppuccin-mocha"
#   custom_css_path: "./styles/catppuccin-mocha.css"

# catppuccin-latte
# styling:
#   font_family: "Calibri, Arial, sans-serif"
#   font_size: "9.5pt"
#   margin_size: "3px"
#   theme: "catppuccin_latte"
#   custom_css_path: "./styles/catppuccin-latte.css"

# base
# styling:
#   font_family: "Calibri, Arial, sans-serif"
#   font_size: "9.5pt"
#   margin_size: "3px"
#   theme: "base"
#   custom_css_path: "./styles/base.css"

# nord
# styling:
#   font_family: "Calibri, Arial, sans-serif"
#   font_size: "9.5pt"
#   margin_size: "3px"
#   theme: "nord"
#   custom_css_path: "./styles/nord.css"

# tokyonight
# styling:
#   font_family: "Calibri, Arial, sans-serif"
#   font_size: "9.5pt"
#   margin_size: "3px"
#   theme: "tokyonight"
#   custom_css_path: "./styles/tokyonight.css"

# default
# styling:
#   font_family: "Calibri, Arial, sans-serif"
#   font_size: "9.5pt"
#   margin_size: "3px"
#   theme: "default"
#   custom_css_path: "./styles/default.css"

# modern-clean
# styling:
#   font_family: "Calibri, Arial, sans-serif"
#   font_size: "10.5pt"
#   margin_size: "0.5in"
#   theme: "modern_clean"
#   custom_css_path: "./styles/modern-clean.css"

# minimal-light (new light theme)
styling:
  font_family: "Georgia, Times New Roman, serif"
  font_size: "10.5pt"
  margin_size: "0.5in"
  theme: "minimal_light"
  custom_css_path: "./styles/minimal-light.css"

# elegant-light (new light theme)
# styling:
#   font_family: "Garamond, Times New Roman, serif"
#   font_size: "10.5pt"
#   margin_size: "0.5in"
#   theme: "elegant_light"
#   custom_css_path: "./styles/elegant-light.css"
#
# fresh-light (new light theme)
# styling:
#   font_family: "Helvetica Neue, Arial, sans-serif"
#   font_size: "10.5pt"
#   margin_size: "0.5in"
#   theme: "fresh_light"
#   custom_css_path: "./styles/fresh-light.css"

# corporate-light (new light theme)
# styling:
#   font_family: "Calibri, Arial, sans-serif"
#   font_size: "10.5pt"
#   margin_size: "0.5in"
#   theme: "corporate_light"
#   custom_css_path: "./styles/corporate-light.css"

# default
# styling:
#   font_family: "Calibri, Arial, sans-serif"
#   font_size: "9.5pt"
#   margin_size: "3px"
#   theme: "default"
#   custom_css_path: "./styles/default.css"

paths:
  styles_dir: "./styles"
  template_file: "./templates/resume.html"
  theme_files:
    base: "base.css"
    ats: "ats.css"
    default: "default.css"
    tokyonight: "tokyonight.css"
    catppuccin_mocha: "catppuccin-mocha.css"
    catppuccin_latte: "catppuccin-latte.css"
    modern_clean: "modern-clean.css"
    nord: "nord.css"
    github_dark: "github-dark.css"
    professional: "professional.css"
    minimal_light: "minimal-light.css"
    elegant_light: "elegant-light.css"
    fresh_light: "fresh-light.css"
    corporate_light: "corporate-light.css"
pdf:
  dpi: 300
  page_size: "A4"
  page_divisions: false
  margin_top: 1
  margin_bottom: 1
  margin_left: 1
  margin_right: 1
  unicode_enabled: true

# Logging configuration
logging:
  level: "info" # debug, info, warn, error
  log_file: "" # Leave empty for stderr, or specify file path like "cv-gen.log"
  pretty: true # Pretty print logs to console
