# Resume Generator Configuration
general:
  input_file: "./artifacts/input_markdown_resumes/akhil-polyglot.md"
  output_file: "./artifacts/output_cvs/akhil_cv.pdf"
mode: "custom"
styling:
  font_family: "Hack Nerd Font"
  font_size: "12px"
  margin_size: "5px"
  theme: "catppuccin-mocha"
paths:
  styles_dir: "./styles"
  template_file: "./templates/resume.html"
  theme_files:
    base: "base.css"
    ats: "ats.css"
    default: "default.css"
    tokyonight: "tokyonight.css"
    catppuccin_mocha: "catppuccin-mocha.css"
    catppuccin_latte: "catppuccin-latte.css"
    modern_clean: "modern-clean.css"
    nord: "nord.css"
    github_dark: "github-dark.css"
pdf:
  dpi: 300
  page_size: "A4"
  page_divisions: false
  margin_top: 5
  margin_bottom: 5
  margin_left: 5
  margin_right: 5
  unicode_enabled: true
