# Resume Generator Configuration
general:
  input_file: "./artifacts/input_markdown_resumes/akhil-hft.md"
  output_file: "./artifacts/output_cvs/akhil_hft00.pdf"
mode: "ats"
styling:
  font_family: "Arial, sans-serif"
  font_size: "12px"
  margin_size: "5px"
  theme: "professional"
paths:
  styles_dir: "./styles"
  template_file: "./templates/resume.html"
  theme_files:
    base: "base.css"
    ats: "ats.css"
    default: "default.css"
    tokyonight: "tokyonight.css"
    catppuccin_mocha: "catppuccin-mocha.css"
    catppuccin_latte: "catppuccin-latte.css"
    modern_clean: "modern-clean.css"
    nord: "nord.css"
    github_dark: "github-dark.css"
    professional: "professional.css"
pdf:
  dpi: 300
  page_size: "A4"
  page_divisions: false
  margin_top: 3
  margin_bottom: 2
  margin_left: 3
  margin_right: 3
  unicode_enabled: true
